In [7]:
%pip install numpy pillow

  Using cached Pillow-9.0.1-cp39-cp39-macosx_10_10_x86_64.whl (3.0 MB)
You should consider upgrading via the '/usr/local/Cellar/jupyterlab/3.3.0/libexec/bin/python3.9 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [8]:
#!/usr/bin/python3
# font obtained from https://opengameart.org/content/dos-8x8-font
spacing = 1
grid_width = 16
grid_height = 16
import numpy as np

from PIL import Image
filepath = "font.png"
im = Image.open(filepath, 'r')
im_width, im_height = im.size
assert im_width == grid_width*8 + (grid_width+1)
assert im_height == grid_height*8 + (grid_height+1)
is_white_pixel = lambda pixel: int(pixel == (255, 255, 255, 255))
pixel_list = [is_white_pixel(p) for p in im.getdata()]
pixel_grid = np.array(pixel_list).reshape(im_width, im_height)
bits_to_byte = lambda bits: int("".join(map(str, bits)), 2)

In [25]:
output = []
for row in range(grid_height):
    for col in range(grid_width):
        x_start = 1 + row + row*8
        y_start = 1 + col + col*8
        char_data = pixel_grid[x_start:x_start+8, y_start:y_start+8]

        hex_string = ",".join([hex(bits_to_byte(byte)) for byte in char_data.T])
        output.append(hex_string)

In [27]:
row = 4
col = 1
x_start = 1 + row + row*8
y_start = 1 + col + col*8
char_data = pixel_grid[x_start:x_start+8, y_start:y_start+8]
d = [np.roll(i, 1) for i in char_data.T]
d

[array([0, 0, 0, 1, 1, 1, 1, 1]),
 array([0, 0, 1, 1, 1, 1, 1, 1]),
 array([0, 1, 1, 0, 0, 1, 0, 0]),
 array([0, 1, 1, 0, 0, 1, 0, 0]),
 array([0, 0, 1, 1, 1, 1, 1, 1]),
 array([0, 0, 0, 1, 1, 1, 1, 1]),
 array([0, 0, 0, 0, 0, 0, 0, 0]),
 array([0, 0, 0, 0, 0, 0, 0, 0])]